version: '3'

services:
  aui-person:
    image: aui-person:1.0
    restart: always
    networks:
      - aui-network
    ports:
      - "8081:8080"

  aui-job:
    image: aui-job:1.0
    restart: always
    environment:
      AUI_CHARACTER_URL: "http://aui-person:8080"
    networks:
      - aui-network
    ports:
      - "8082:8080"

  aui-gateway:
    image: aui-gateway:1.0
    restart: always
    environment:
      AUI_CHARACTER_URL: "http://aui-person:8080"
      AUI_PROFESSION_URL: "http://aui-job:8080"
      AUI_GATEWAY_HOST: "aui-gateway:8080"
    ports:
      - "8080:8080"
    networks:
      - aui-network

  aui-ng:
    image: aui-angular:1.0
    restart: always
    environment:
      API_URL: "http://aui-gateway:8080/work"
    ports:
      - "8085:80"
    networks:
      - aui-network

  person-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: "person_db"
      POSTGRES_USER: "person_user"
      POSTGRES_PASSWORD: "person_password"
    volumes:
      - person-db-data:/var/lib/postgresql/data
    networks:
      - aui-network

  job-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: "job_db"
      POSTGRES_USER: "job_user"
      POSTGRES_PASSWORD: "job_password"
    volumes:
      - job-db-data:/var/lib/postgresql/data
    networks:
      - aui-network



networks:
  aui-network:
    driver: bridge